// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sukfbhgbbfpfomjympvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1a2ZiaGdiYmZwZm9tanltcHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTM1MTEsImV4cCI6MjA2MzU4OTUxMX0.Ak5hpNa0BmCkZJ_LtGk9CJFG6pqVk-xiEhWmmkeqg4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);